version: "3.2"
services:
  rabbitmq:
    build: .
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./rabbit_data/data/:/var/lib/rabbitmq/:rw
        - ./rabbit_data/log/:/var/log/rabbitmq:rw
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge