# Use root/example as user/password credentials
version: '3.1'

services:

  team_management_db:
    image: mariadb
    restart: always
    ports:
      - 3308:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: team_mgmt
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
    volumes:
     - ${PWD}/data/mariadb_teams:/var/lib/mysql

  project_management_db:
    image: mariadb
    restart: always
    ports:
      - 3309:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: project_mgmt
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev
    volumes:
     - ${PWD}/data/mariadb_project:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080